"""empty message

Revision ID: 947ace485d78
Revises: 
Create Date: 2024-08-10 16:13:18.875114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '947ace485d78'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
